- name: Docker
  hosts: ubuntu
  
  tasks:  
  - name: Install required packages
    ansible.builtin.apt:
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      state: latest
      update_cache: true
    become: true
  
  - name: Add Docker\'s official GPG key
    ansible.builtin.apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true

  - name: Add repository into sources list
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
      filename: docker
    become: true

  - name: Install Docker
    ansible.builtin.apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      state: latest
      update_cache: true
    become: true

  - name: Add your user to the docker group.
    ansible.builtin.shell: sudo groupadd docker || echo "exists" && sudo usermod -aG docker $USER

- name: run nginx container 
  hosts: ubuntu
  become: true

  tasks:
    - name: run nginx container
      community.docker.docker_container:
        name: nginx
        image: nginxdemos/hello
        ports:
          - "80:80"
